#!/bin/bash
set -e

ENVIRONMENT=$1
HELM_CHART_VERSION=$2
IMAGE_TAG=$3

if [ -z "$ENVIRONMENT" ] || [ -z "$HELM_CHART_VERSION" ] || [ -z "$IMAGE_TAG" ]; then
    echo "Usage: $0 <environment> <helm_chart_version> <image_tag>"
    exit 1
fi

echo "========================================="
echo "Stage 6: Updating Config Repository"
echo "========================================="
echo "Environment: $ENVIRONMENT"
echo "Helm Chart Version: $HELM_CHART_VERSION"
echo "Image Tag: $IMAGE_TAG"
echo "========================================="

# Construct AWS_ECR_REGISTRY and PROJECT_NAME
AWS_ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
PROJECT_NAME=$(basename "${GITHUB_REPOSITORY:-SRE-Project-1-AWS-EKS-GitHub-Actions-Argocd}")

echo "Updating config for project: $PROJECT_NAME in $AWS_ECR_REGISTRY"

# Create or update config.yaml for the environment
CONFIG_FILE="environments/${ENVIRONMENT}/config.yaml"
mkdir -p "environments/${ENVIRONMENT}"

cat > $CONFIG_FILE <<EOF
# Auto-generated by CI/CD Pipeline
# Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Commit: ${GITHUB_SHA}
# Pipeline: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}

application:
  name: ${PROJECT_NAME}
  environment: ${ENVIRONMENT}

helm:
  chart:
    repository: oci://${AWS_ECR_REGISTRY}/helm-charts
    name: ${PROJECT_NAME}
    version: ${HELM_CHART_VERSION}
  
  values:
    image:
      repository: ${AWS_ECR_REGISTRY}/${PROJECT_NAME}
      tag: ${IMAGE_TAG}
    
    replicaCount: 2
    
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

terraform:
  version: "1.6.0"
  
deployment:
  timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
  triggeredBy: ${GITHUB_ACTOR}
  commitSha: ${GITHUB_SHA}
  branch: ${GITHUB_REF_NAME}
EOF

echo "✅ Created config file: $CONFIG_FILE"
cat $CONFIG_FILE

# Commit and push changes
echo ""
echo "Committing changes to config repository..."
git add $CONFIG_FILE

# Check if there are changes to commit
if git diff --staged --quiet; then
    echo "No changes to commit."
else
    git commit -m "Update ${ENVIRONMENT} config - Helm: ${HELM_CHART_VERSION}, Image: ${IMAGE_TAG}

Triggered by: ${GITHUB_ACTOR}
Pipeline: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
Commit: ${GITHUB_SHA}"

    git push origin HEAD:${GITHUB_REF_NAME}
fi

echo ""
echo "========================================="
echo "✅ Config repository updated successfully"
echo "ArgoCD will detect changes and deploy to ${ENVIRONMENT}"
echo "========================================="
